# Generated by Django 5.2.5 on 2025-09-06 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0002_alter_botuser_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindmapProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('background_color', models.CharField(default='#ffffff', help_text='Hex color code', max_length=7)),
                ('grid_enabled', models.BooleanField(default=True)),
                ('snap_to_grid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mindmap_projects', to='webapp.botuser')),
            ],
            options={
                'verbose_name': 'Mindmap Project',
                'verbose_name_plural': 'Mindmap Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MindmapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('completed', 'Completed'), ('backlog', 'Backlog'), ('cancelled', 'Cancelled')], default='todo', max_length=15)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='med', max_length=10)),
                ('x_position', models.FloatField(default=0)),
                ('y_position', models.FloatField(default=0)),
                ('width', models.IntegerField(default=200)),
                ('height', models.IntegerField(default=80)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mindmap_nodes', to='webapp.botuser')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mindmap_nodes', to='webapp.botuser')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='mindmap.mindmapproject')),
            ],
            options={
                'verbose_name': 'Mindmap Node',
                'verbose_name_plural': 'Mindmap Nodes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MindmapConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(blank=True, default='dependency', max_length=50)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color code', max_length=7)),
                ('thickness', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='mindmap.mindmapnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='mindmap.mindmapnode')),
            ],
            options={
                'verbose_name': 'Mindmap Connection',
                'verbose_name_plural': 'Mindmap Connections',
                'unique_together': {('from_node', 'to_node')},
            },
        ),
    ]
