# Generated by Django 5.2.5 on 2025-09-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_taskactivity_taskattachment_taskcomment_projectlabel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='estimated_hours',
        ),
    ]
