# Generated by Django 5.2.5 on 2025-09-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_estimated_hours_from_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('commented', 'Commented'), ('attachment_added', 'Attachment Added'), ('completed', 'Completed')], max_length=20),
        ),
    ]
